# Generated by Django 6.0.2 on 2026-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Glucose in mg/dL', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='glucose_measurement_type',
            field=models.CharField(blank=True, choices=[('FASTING', 'Fasting'), ('RANDOM', 'Random'), ('POST_MEAL', 'Post Meal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
